name: programme_tv_multisport
description: Programme TV Foot & Multisport par tele-sports.fr

version: 1.0.1+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.2+1
  firebase_storage: ^3.1.1
  equatable: ^1.1.0
  flutter_bloc: ^3.2.0
  intl: ^0.16.1
  path_provider: ^1.6.0
  sticky_headers: ^0.1.8+1
  sqflite: ^1.2.0
  firebase_crashlytics: ^0.1.2+5
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
       - family: Varela
         fonts:
          - asset: assets/fonts/Varela-Regular.ttf