name: programme_tv_multisport
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  equatable: ^1.0.2
  flutter_bloc: ^3.1.0
  intl: ^0.16.1
  path_provider: ^1.5.1
  sticky_headers: ^0.1.8+1
  sqflite: ^1.2.0
  firebase_crashlytics: ^0.1.2+4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true